-- Course: Ballerud Golf
-- Location: Høvik, Norway
-- Type: 9-hole course
-- Generated by parse_scorecard.py
-- Corrected 2026-07-16 against official club data (re-rated August 2024):
--   https://ballerud.no/bane/slopetabeller (Gul/HERRER: Par 54, CR/Slope 53,6/93)
--   https://ballerud.no/bane/scorekort (distances, stroke index)
-- The original scrape stored a 9-hole CR (26.4) as courseRating18 and halved
-- it into impossible per-nine ratings; distances/stroke indexes were stale.
-- See migration 20260716121000_fix_ballerud_yellow_tee_ratings.sql.

do $$
declare
    v_course_id integer;
    v_tee_id_1 integer;
begin

    -- Insert course
    insert into public.course (name, city, country, website, "approvalStatus")
    values ('Ballerud Golf', 'Høvik', 'Norway', 'https://ballerud.no/', 'approved')
    returning id into v_course_id;

    -- Insert Yellow tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus"
    )
    values (
        v_course_id, 'Yellow', 'mens',
        53.6, 93,
        26.8, 93,
        26.8, 93,
        27, 27, 54,
        960, 960, 1920,
        'meters', 'approved'
    )
    returning id into v_tee_id_1;

    -- Holes for Yellow (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 1, 3, 148, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 2, 3, 128, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 3, 3, 67, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 4, 3, 99, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 5, 3, 100, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 6, 3, 97, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 7, 3, 114, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 8, 3, 109, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 9, 3, 98, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 10, 3, 148, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 11, 3, 128, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 12, 3, 67, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 13, 3, 99, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 14, 3, 100, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 15, 3, 97, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 16, 3, 114, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 17, 3, 109, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 18, 3, 98, 10);

    raise notice 'Successfully inserted course: %', v_course_id;
end $$;
