-- Course: Bathgate Golf Club
-- Location: Bathgate, Scotland
-- Type: 18-hole course
-- Generated by course-ingest

do $$
declare
    v_course_id integer;
    v_tee_id_1 integer;
    v_tee_id_2 integer;
    v_tee_id_3 integer;
begin

    -- Insert course
    insert into public.course (name, city, country, website, "approvalStatus", "submittedBy")
    values ('Bathgate Golf Club', 'Bathgate', 'Scotland', 'https://www.bathgategolfclub.com', 'approved', null)
    returning id into v_course_id;

    -- Insert White tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'White', 'mens',
        71.7, 129,
        35.9, 129,
        35.9, 129,
        36, 35, 71,
        3218, 3110, 6328,
        'yards', 'approved', null
    )
    returning id into v_tee_id_1;

    -- Holes for White (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 1, 5, 476, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 2, 4, 451, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 3, 4, 329, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 4, 3, 216, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 5, 5, 480, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 6, 4, 402, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 7, 4, 373, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 8, 3, 145, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 9, 4, 346, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 10, 4, 398, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 11, 3, 175, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 12, 5, 505, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 13, 3, 215, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 14, 4, 429, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 15, 5, 504, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 16, 4, 337, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 17, 3, 142, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 18, 4, 405, 4);

    -- Insert Yellow tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Yellow', 'mens',
        69.3, 126,
        34.7, 126,
        34.7, 126,
        36, 35, 71,
        3020, 2846, 5866,
        'yards', 'approved', null
    )
    returning id into v_tee_id_2;

    -- Holes for Yellow (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 1, 5, 462, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 2, 4, 427, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 3, 4, 307, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 4, 3, 177, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 5, 5, 454, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 6, 4, 396, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 7, 4, 368, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 8, 3, 131, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 9, 4, 298, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 10, 4, 343, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 11, 3, 158, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 12, 5, 483, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 13, 3, 206, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 14, 4, 419, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 15, 5, 470, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 16, 4, 286, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 17, 3, 134, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 18, 4, 347, 4);

    -- Insert Red tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Red', 'ladies',
        70.7, 127,
        35.4, 127,
        35.4, 127,
        35, 35, 70,
        2628, 2524, 5152,
        'yards', 'approved', null
    )
    returning id into v_tee_id_3;

    -- Holes for Red (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 1, 5, 450, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 2, 4, 380, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 3, 4, 229, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 4, 3, 155, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 5, 4, 327, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 6, 4, 340, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 7, 4, 334, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 8, 3, 123, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 9, 4, 290, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 10, 4, 311, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 11, 3, 146, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 12, 5, 425, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 13, 3, 186, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 14, 4, 353, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 15, 5, 420, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 16, 4, 278, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 17, 3, 115, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 18, 4, 290, 15);

    raise notice 'Successfully inserted course: %', v_course_id;
end $$;
