-- Course: Bruntsfield Links Golfing Society
-- Location: Edinburgh, Scotland
-- Type: 18-hole course
-- Generated by course-ingest

do $$
declare
    v_course_id integer;
    v_tee_id_1 integer;
    v_tee_id_2 integer;
    v_tee_id_3 integer;
    v_tee_id_4 integer;
    v_tee_id_5 integer;
    v_tee_id_6 integer;
begin

    -- Insert course
    insert into public.course (name, city, country, website, "approvalStatus", "submittedBy")
    values ('Bruntsfield Links Golfing Society', 'Edinburgh', 'Scotland', 'http://www.bruntsfieldlinks.co.uk', 'approved', null)
    returning id into v_course_id;

    -- Insert White tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'White', 'mens',
        72.0, 126,
        36.0, 126,
        36.0, 126,
        36, 35, 71,
        3324, 3142, 6466,
        'yards', 'approved', null
    )
    returning id into v_tee_id_1;

    -- Holes for White (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 1, 4, 427, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 2, 4, 383, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 3, 4, 368, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 4, 5, 543, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 5, 3, 203, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 6, 4, 356, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 7, 3, 154, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 8, 4, 379, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 9, 5, 511, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 10, 3, 144, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 11, 4, 423, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 12, 5, 549, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 13, 5, 510, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 14, 3, 181, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 15, 4, 372, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 16, 3, 170, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 17, 4, 450, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 18, 4, 343, 10);

    -- Insert White tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'White', 'ladies',
        77.8, 132,
        38.9, 132,
        38.9, 132,
        37, 37, 74,
        3324, 3142, 6466,
        'yards', 'approved', null
    )
    returning id into v_tee_id_2;

    -- Holes for White (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 1, 5, 427, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 2, 4, 383, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 3, 4, 368, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 4, 5, 543, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 5, 3, 203, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 6, 4, 356, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 7, 3, 154, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 8, 4, 379, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 9, 5, 511, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 10, 3, 144, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 11, 5, 423, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 12, 5, 549, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 13, 5, 510, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 14, 3, 181, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 15, 4, 372, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 16, 3, 170, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 17, 5, 450, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 18, 4, 343, 10);

    -- Insert Yellow tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Yellow', 'mens',
        70.5, 124,
        35.3, 124,
        35.3, 124,
        36, 35, 71,
        3163, 2969, 6132,
        'yards', 'approved', null
    )
    returning id into v_tee_id_3;

    -- Holes for Yellow (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 1, 4, 396, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 2, 4, 366, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 3, 4, 342, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 4, 5, 527, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 5, 3, 195, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 6, 4, 342, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 7, 3, 145, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 8, 4, 348, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 9, 5, 502, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 10, 3, 132, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 11, 4, 414, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 12, 5, 514, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 13, 5, 506, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 14, 3, 172, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 15, 4, 357, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 16, 3, 154, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 17, 4, 402, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 18, 4, 318, 10);

    -- Insert Yellow tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Yellow', 'ladies',
        75.9, 128,
        38.0, 128,
        38.0, 128,
        36, 37, 73,
        3163, 2969, 6132,
        'yards', 'approved', null
    )
    returning id into v_tee_id_4;

    -- Holes for Yellow (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 1, 4, 396, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 2, 4, 366, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 3, 4, 342, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 4, 5, 527, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 5, 3, 195, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 6, 4, 342, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 7, 3, 145, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 8, 4, 348, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 9, 5, 502, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 10, 3, 132, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 11, 5, 414, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 12, 5, 514, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 13, 5, 506, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 14, 3, 172, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 15, 4, 357, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 16, 3, 154, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 17, 5, 402, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 18, 4, 318, 10);

    -- Insert Blue tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Blue', 'mens',
        67.6, 118,
        33.8, 118,
        33.8, 118,
        35, 34, 69,
        2915, 2584, 5499,
        'yards', 'approved', null
    )
    returning id into v_tee_id_5;

    -- Holes for Blue (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 1, 4, 352, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 2, 4, 344, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 3, 4, 324, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 4, 4, 442, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 5, 3, 178, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 6, 4, 327, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 7, 3, 136, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 8, 4, 339, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 9, 5, 473, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 10, 3, 113, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 11, 4, 373, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 12, 5, 465, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 13, 4, 449, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 14, 3, 153, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 15, 4, 305, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 16, 3, 125, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 17, 4, 306, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 18, 4, 295, 10);

    -- Insert Red tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Red', 'ladies',
        72.4, 121,
        36.2, 121,
        36.2, 121,
        36, 35, 71,
        2915, 2584, 5499,
        'yards', 'approved', null
    )
    returning id into v_tee_id_6;

    -- Holes for Red (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 1, 4, 352, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 2, 4, 344, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 3, 4, 324, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 4, 5, 442, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 5, 3, 178, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 6, 4, 327, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 7, 3, 136, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 8, 4, 339, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 9, 5, 473, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 10, 3, 113, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 11, 4, 373, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 12, 5, 465, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 13, 5, 449, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 14, 3, 153, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 15, 4, 305, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 16, 3, 125, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 17, 4, 306, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 18, 4, 295, 10);

    raise notice 'Successfully inserted course: %', v_course_id;
end $$;
