-- Course: Fet Golfklubb & Leikvin Golfpark
-- Location: Fetsund, Norway
-- Type: 9-hole course
-- Generated by parse_scorecard.py

do $$
declare
    v_course_id integer;
    v_tee_id_1 integer;
    v_tee_id_2 integer;
    v_tee_id_3 integer;
    v_tee_id_4 integer;
begin

    -- Insert course
    insert into public.course (name, city, country, website, "approvalStatus")
    values ('Fet Golfklubb & Leikvin Golfpark', 'Fetsund', 'Norway', 'https://www.fetgk.no/', 'approved')
    returning id into v_course_id;

    -- Insert White tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus"
    )
    values (
        v_course_id, 'White', 'mens',
        56.9, 87,
        28.4, 87,
        28.4, 87,
        28, 28, 56,
        1405, 1405, 2810,
        'meters', 'approved'
    )
    returning id into v_tee_id_1;

    -- Insert White tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus"
    )
    values (
        v_course_id, 'White', 'ladies',
        57.6, 97,
        28.8, 97,
        28.8, 97,
        28, 28, 56,
        1405, 1405, 2810,
        'meters', 'approved'
    )
    returning id into v_tee_id_2;

    -- Insert Red tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus"
    )
    values (
        v_course_id, 'Red', 'mens',
        56.7, 87,
        28.4, 87,
        28.4, 87,
        28, 28, 56,
        1375, 1375, 2750,
        'meters', 'approved'
    )
    returning id into v_tee_id_3;

    -- Insert Red tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus"
    )
    values (
        v_course_id, 'Red', 'ladies',
        57.5, 94,
        28.8, 94,
        28.8, 94,
        28, 28, 56,
        1375, 1375, 2750,
        'meters', 'approved'
    )
    returning id into v_tee_id_4;

    -- Holes for White (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 1, 4, 350, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 2, 3, 85, 25);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 3, 3, 124, 21);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 4, 3, 125, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 5, 3, 178, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 6, 3, 137, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 7, 3, 122, 33);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 8, 3, 136, 29);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 9, 3, 148, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 10, 4, 350, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 11, 3, 85, 26);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 12, 3, 124, 22);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 13, 3, 125, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 14, 3, 178, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 15, 3, 137, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 16, 3, 122, 34);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 17, 3, 136, 30);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 18, 3, 148, 14);

    -- Holes for White (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 1, 4, 350, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 2, 3, 85, 25);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 3, 3, 124, 21);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 4, 3, 125, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 5, 3, 178, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 6, 3, 137, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 7, 3, 122, 33);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 8, 3, 136, 29);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 9, 3, 148, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 10, 4, 350, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 11, 3, 85, 26);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 12, 3, 124, 22);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 13, 3, 125, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 14, 3, 178, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 15, 3, 137, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 16, 3, 122, 34);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 17, 3, 136, 30);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 18, 3, 148, 14);

    -- Holes for Red (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 1, 4, 350, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 2, 3, 85, 25);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 3, 3, 124, 21);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 4, 3, 125, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 5, 3, 148, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 6, 3, 137, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 7, 3, 122, 33);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 8, 3, 136, 29);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 9, 3, 148, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 10, 4, 350, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 11, 3, 85, 26);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 12, 3, 124, 22);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 13, 3, 125, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 14, 3, 148, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 15, 3, 137, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 16, 3, 122, 34);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 17, 3, 136, 30);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 18, 3, 148, 14);

    -- Holes for Red (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 1, 4, 350, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 2, 3, 85, 25);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 3, 3, 124, 21);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 4, 3, 125, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 5, 3, 148, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 6, 3, 137, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 7, 3, 122, 33);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 8, 3, 136, 29);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 9, 3, 148, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 10, 4, 350, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 11, 3, 85, 26);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 12, 3, 124, 22);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 13, 3, 125, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 14, 3, 148, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 15, 3, 137, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 16, 3, 122, 34);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 17, 3, 136, 30);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 18, 3, 148, 14);

    raise notice 'Successfully inserted course: %', v_course_id;
end $$;