-- Course: Sorknes Golfklubb
-- Location: Rena, Norway
-- Type: 18-hole course
-- Generated by course-ingest

do $$
declare
    v_course_id integer;
    v_tee_id_1 integer;
    v_tee_id_2 integer;
    v_tee_id_3 integer;
    v_tee_id_4 integer;
    v_tee_id_5 integer;
    v_tee_id_6 integer;
    v_tee_id_7 integer;
begin

    -- Insert course
    insert into public.course (name, city, country, website, "approvalStatus", "submittedBy")
    values ('Sorknes Golfklubb', 'Rena', 'Norway', 'https://www.sorknesgk.no', 'approved', null)
    returning id into v_course_id;

    -- Insert 61 tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, '61', 'mens',
        74.0, 140,
        37.0, 140,
        37.0, 140,
        36, 36, 72,
        3060, 3045, 6105,
        'meters', 'approved', null
    )
    returning id into v_tee_id_1;

    -- Holes for 61 (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 1, 4, 320, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 2, 4, 400, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 3, 5, 510, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 4, 3, 180, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 5, 4, 285, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 6, 4, 395, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 7, 3, 140, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 8, 4, 380, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 9, 5, 450, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 10, 4, 360, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 11, 5, 515, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 12, 4, 335, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 13, 3, 155, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 14, 4, 365, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 15, 4, 355, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 16, 5, 455, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 17, 3, 135, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 18, 4, 370, 7);

    -- Insert 56 tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, '56', 'mens',
        71.9, 136,
        36.0, 136,
        36.0, 136,
        36, 36, 72,
        2845, 2850, 5695,
        'meters', 'approved', null
    )
    returning id into v_tee_id_2;

    -- Holes for 56 (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 1, 4, 310, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 2, 4, 370, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 3, 5, 460, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 4, 3, 175, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 5, 4, 285, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 6, 4, 360, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 7, 3, 130, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 8, 4, 325, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 9, 5, 430, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 10, 4, 350, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 11, 5, 505, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 12, 4, 285, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 13, 3, 120, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 14, 4, 350, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 15, 4, 340, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 16, 5, 440, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 17, 3, 130, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 18, 4, 330, 7);

    -- Insert 51 tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, '51', 'mens',
        69.0, 131,
        34.5, 131,
        34.5, 131,
        36, 36, 72,
        2540, 2565, 5105,
        'meters', 'approved', null
    )
    returning id into v_tee_id_3;

    -- Holes for 51 (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 1, 4, 275, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 2, 4, 315, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 3, 5, 415, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 4, 3, 140, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 5, 4, 270, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 6, 4, 305, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 7, 3, 120, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 8, 4, 285, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 9, 5, 415, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 10, 4, 300, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 11, 5, 430, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 12, 4, 280, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 13, 3, 110, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 14, 4, 310, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 15, 4, 310, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 16, 5, 375, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 17, 3, 130, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 18, 4, 320, 7);

    -- Insert 47 tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, '47', 'mens',
        67.2, 125,
        33.6, 125,
        33.6, 125,
        36, 36, 72,
        2330, 2420, 4750,
        'meters', 'approved', null
    )
    returning id into v_tee_id_4;

    -- Holes for 47 (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 1, 4, 265, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 2, 4, 310, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 3, 5, 395, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 4, 3, 130, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 5, 4, 250, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 6, 4, 295, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 7, 3, 115, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 8, 4, 230, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 9, 5, 340, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 10, 4, 290, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 11, 5, 425, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 12, 4, 230, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 13, 3, 100, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 14, 4, 300, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 15, 4, 300, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 16, 5, 375, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 17, 3, 120, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 18, 4, 280, 7);

    -- Insert 56 tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, '56', 'ladies',
        77.9, 143,
        39.0, 143,
        39.0, 143,
        36, 36, 72,
        2845, 2850, 5695,
        'meters', 'approved', null
    )
    returning id into v_tee_id_5;

    -- Holes for 56 (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 1, 4, 310, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 2, 4, 370, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 3, 5, 460, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 4, 3, 175, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 5, 4, 285, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 6, 4, 360, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 7, 3, 130, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 8, 4, 325, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 9, 5, 430, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 10, 4, 350, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 11, 5, 505, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 12, 4, 285, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 13, 3, 120, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 14, 4, 350, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 15, 4, 340, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 16, 5, 440, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 17, 3, 130, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 18, 4, 330, 7);

    -- Insert 51 tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, '51', 'ladies',
        74.3, 133,
        37.2, 133,
        37.2, 133,
        36, 36, 72,
        2540, 2565, 5105,
        'meters', 'approved', null
    )
    returning id into v_tee_id_6;

    -- Holes for 51 (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 1, 4, 275, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 2, 4, 315, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 3, 5, 415, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 4, 3, 140, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 5, 4, 270, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 6, 4, 305, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 7, 3, 120, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 8, 4, 285, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 9, 5, 415, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 10, 4, 300, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 11, 5, 430, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 12, 4, 280, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 13, 3, 110, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 14, 4, 310, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 15, 4, 310, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 16, 5, 375, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 17, 3, 130, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 18, 4, 320, 7);

    -- Insert 47 tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, '47', 'ladies',
        72.0, 130,
        36.0, 130,
        36.0, 130,
        36, 36, 72,
        2330, 2420, 4750,
        'meters', 'approved', null
    )
    returning id into v_tee_id_7;

    -- Holes for 47 (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 1, 4, 265, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 2, 4, 310, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 3, 5, 395, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 4, 3, 130, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 5, 4, 250, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 6, 4, 295, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 7, 3, 115, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 8, 4, 230, 8);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 9, 5, 340, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 10, 4, 290, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 11, 5, 425, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 12, 4, 230, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 13, 3, 100, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 14, 4, 300, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 15, 4, 300, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 16, 5, 375, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 17, 3, 120, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_7, 18, 4, 280, 7);

    raise notice 'Successfully inserted course: %', v_course_id;
end $$;
