-- Course: Tyrifjord Golfklubb
-- Location: Krokkleiva, Norway
-- Type: 18-hole course
-- Generated by course-ingest

do $$
declare
    v_course_id integer;
    v_tee_id_1 integer;
    v_tee_id_2 integer;
    v_tee_id_3 integer;
    v_tee_id_4 integer;
    v_tee_id_5 integer;
    v_tee_id_6 integer;
begin

    -- Insert course
    insert into public.course (name, city, country, website, "approvalStatus", "submittedBy")
    values ('Tyrifjord Golfklubb', 'Krokkleiva', 'Norway', 'https://tyrifjord-golfklubb.no', 'approved', null)
    returning id into v_course_id;

    -- Insert Hvit tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Hvit', 'mens',
        71.3, 135,
        35.7, 135,
        35.7, 135,
        36, 36, 72,
        2845, 2791, 5636,
        'meters', 'approved', null
    )
    returning id into v_tee_id_1;

    -- Holes for Hvit (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 1, 4, 339, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 2, 4, 317, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 3, 3, 119, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 4, 4, 333, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 5, 5, 476, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 6, 3, 131, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 7, 4, 321, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 8, 4, 291, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 9, 5, 518, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 10, 3, 136, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 11, 5, 439, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 12, 4, 337, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 13, 3, 162, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 14, 4, 292, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 15, 4, 364, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 16, 5, 431, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 17, 4, 312, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_1, 18, 4, 318, 8);

    -- Insert Gul tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Gul', 'mens',
        69.9, 133,
        35.0, 133,
        35.0, 133,
        36, 36, 72,
        2754, 2696, 5450,
        'meters', 'approved', null
    )
    returning id into v_tee_id_2;

    -- Holes for Gul (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 1, 4, 326, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 2, 4, 306, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 3, 3, 101, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 4, 4, 327, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 5, 5, 471, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 6, 3, 118, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 7, 4, 317, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 8, 4, 276, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 9, 5, 512, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 10, 3, 123, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 11, 5, 425, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 12, 4, 329, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 13, 3, 154, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 14, 4, 281, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 15, 4, 348, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 16, 5, 423, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 17, 4, 301, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_2, 18, 4, 312, 8);

    -- Insert Rød tee (mens)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Rød', 'mens',
        67.2, 127,
        33.6, 127,
        33.6, 127,
        36, 36, 72,
        2437, 2362, 4799,
        'meters', 'approved', null
    )
    returning id into v_tee_id_3;

    -- Holes for Rød (mens)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 1, 4, 291, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 2, 4, 280, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 3, 3, 92, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 4, 4, 299, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 5, 5, 419, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 6, 3, 81, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 7, 4, 284, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 8, 4, 251, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 9, 5, 440, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 10, 3, 114, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 11, 5, 401, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 12, 4, 283, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 13, 3, 134, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 14, 4, 241, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 15, 4, 289, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 16, 5, 357, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 17, 4, 276, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_3, 18, 4, 267, 8);

    -- Insert Hvit tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Hvit', 'ladies',
        76.4, 142,
        38.2, 142,
        38.2, 142,
        36, 36, 72,
        2845, 2791, 5636,
        'meters', 'approved', null
    )
    returning id into v_tee_id_4;

    -- Holes for Hvit (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 1, 4, 339, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 2, 4, 317, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 3, 3, 119, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 4, 4, 333, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 5, 5, 476, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 6, 3, 131, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 7, 4, 321, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 8, 4, 291, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 9, 5, 518, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 10, 3, 136, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 11, 5, 439, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 12, 4, 337, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 13, 3, 162, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 14, 4, 292, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 15, 4, 364, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 16, 5, 431, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 17, 4, 312, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_4, 18, 4, 318, 8);

    -- Insert Gul tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Gul', 'ladies',
        74.2, 143,
        37.1, 143,
        37.1, 143,
        36, 36, 72,
        2754, 2696, 5450,
        'meters', 'approved', null
    )
    returning id into v_tee_id_5;

    -- Holes for Gul (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 1, 4, 326, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 2, 4, 306, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 3, 3, 101, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 4, 4, 327, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 5, 5, 471, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 6, 3, 118, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 7, 4, 317, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 8, 4, 276, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 9, 5, 512, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 10, 3, 123, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 11, 5, 425, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 12, 4, 329, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 13, 3, 154, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 14, 4, 281, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 15, 4, 348, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 16, 5, 423, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 17, 4, 301, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_5, 18, 4, 312, 8);

    -- Insert Rød tee (ladies)
    insert into public."teeInfo" (
        "courseId", name, gender,
        "courseRating18", "slopeRating18",
        "courseRatingFront9", "slopeRatingFront9",
        "courseRatingBack9", "slopeRatingBack9",
        "outPar", "inPar", "totalPar",
        "outDistance", "inDistance", "totalDistance",
        "distanceMeasurement", "approvalStatus", "submittedBy"
    )
    values (
        v_course_id, 'Rød', 'ladies',
        71.3, 134,
        35.7, 134,
        35.7, 134,
        36, 36, 72,
        2437, 2362, 4799,
        'meters', 'approved', null
    )
    returning id into v_tee_id_6;

    -- Holes for Rød (ladies)
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 1, 4, 291, 7);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 2, 4, 280, 5);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 3, 3, 92, 15);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 4, 4, 299, 13);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 5, 5, 419, 3);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 6, 3, 81, 11);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 7, 4, 284, 1);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 8, 4, 251, 17);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 9, 5, 440, 9);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 10, 3, 114, 18);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 11, 5, 401, 2);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 12, 4, 283, 10);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 13, 3, 134, 14);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 14, 4, 241, 12);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 15, 4, 289, 4);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 16, 5, 357, 16);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 17, 4, 276, 6);
    insert into public.hole ("teeId", "holeNumber", par, distance, hcp)
    values (v_tee_id_6, 18, 4, 267, 8);

    raise notice 'Successfully inserted course: %', v_course_id;
end $$;
