export const defaultTee = {
  name: "",
  courseRating18: 0,
  slopeRating18: 0,
  courseRatingFront9: 0,
  slopeRatingFront9: 0,
  courseRatingBack9: 0,
  slopeRatingBack9: 0,
  outPar: 0,
  inPar: 0,
  totalPar: 0,
  outDistance: 0,
  inDistance: 0,
  totalDistance: 0,
  gender: "mens" as "mens" | "ladies",
  distanceMeasurement: "meters" as "meters" | "yards",
  holes: [
    {
      holeNumber: 1,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 2,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 3,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 4,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 5,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 6,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 7,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 8,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 9,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 10,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 11,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 12,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 13,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 14,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 15,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 16,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 17,
      par: 0,
      hcp: 0,
      distance: 0,
    },
    {
      holeNumber: 18,
      par: 0,
      hcp: 0,
      distance: 0,
    },
  ],
  approvalStatus: "pending" as "pending" | "approved",
};
