-- -- Fix JSON key in handle_new_user function to match database column name
-- CREATE OR REPLACE FUNCTION public.handle_new_user()
-- RETURNS TRIGGER AS $$
-- DECLARE
--     response_status integer;
-- BEGIN
--     -- Call the create-profile edge function
--     SELECT status INTO response_status
--     FROM http((
--         'POST',
--         current_setting('app.supabase_url', true) || '/functions/v1/create-profile',
--         ARRAY[
--             http_header('Content-Type', 'application/json'),
--             http_header('Authorization', 'Bearer ' || current_setting('app.supabase_anon_key', true))
--         ],
--         'application/json',
--         json_build_object(
--             'userId', NEW.id,
--             'email', NEW.email,
--             'name', COALESCE(NEW.raw_user_meta_data->>'name', ''),
--             'handicap_index', 54
--         )::text
--     ));
    
--     -- Log any non-200 responses (optional)
--     IF response_status != 200 THEN
--         RAISE WARNING 'create-profile edge function returned status: %', response_status;
--     END IF;
    
--     RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql SECURITY DEFINER;
