/**
 * Pure reducer for live round sessions. No React, no Expo, no I/O — every
 * transition is (session, event) → session, and a rejected/no-op event
 * returns the SAME reference so callers can skip persistence and renders.
 * That same-reference rule is also the engine-level double-tap guard.
 */
import { getDisplayedHoles } from "@/lib/scorecard";
import type {
  HoleEntry,
  RoundSession,
  SessionCourse,
  SessionEvent,
} from "@/lib/round-session/types";
import { SESSION_SCHEMA_VERSION } from "@/lib/round-session/types";
import type { Tee } from "@handicappin/handicap-core";

export const MIN_STROKES = 1;
export const MAX_STROKES = 30;

export interface StartSessionParams {
  /** uuid — generated by the caller (expo-crypto) so the engine stays pure. */
  id: string;
  userId: string;
  course: SessionCourse;
  tee: Tee;
  holeCount: 9 | 18;
  nineHoleSection?: "front" | "back";
  /** ISO timestamp for startedAt/lastEventAt. */
  now: string;
}

export function startSession(params: StartSessionParams): RoundSession {
  const { id, userId, course, tee, holeCount, nineHoleSection, now } = params;
  if (holeCount === 9 && nineHoleSection === undefined) {
    throw new Error("nineHoleSection is required for a 9-hole session");
  }
  const displayedHoles = getDisplayedHoles(
    { holes: tee.holes },
    holeCount,
    nineHoleSection ?? "front",
  );
  if (displayedHoles.length !== holeCount) {
    throw new Error(
      `Tee snapshot yielded ${displayedHoles.length} holes, expected ${holeCount}`,
    );
  }
  const entries: HoleEntry[] = Array.from({ length: holeCount }, () => ({
    strokes: null,
    updatedAt: now,
  }));
  return {
    schemaVersion: SESSION_SCHEMA_VERSION,
    id,
    userId,
    status: "active",
    startedAt: now,
    lastEventAt: now,
    eventSeq: 0,
    course,
    tee,
    holeCount,
    ...(holeCount === 9 ? { nineHoleSection } : {}),
    displayedHoles,
    currentHoleIndex: 0,
    entries,
    notes: "",
  };
}

const clampStrokes = (strokes: number): number =>
  Math.min(MAX_STROKES, Math.max(MIN_STROKES, Math.round(strokes)));

const inRange = (s: RoundSession, holeIndex: number): boolean =>
  Number.isInteger(holeIndex) && holeIndex >= 0 && holeIndex < s.holeCount;

/** Accepted event bookkeeping: bump eventSeq, stamp lastEventAt. */
const accept = (s: RoundSession, patch: Partial<RoundSession>, at: string) => ({
  ...s,
  ...patch,
  eventSeq: s.eventSeq + 1,
  lastEventAt: at,
});

export function applyEvent(s: RoundSession, e: SessionEvent): RoundSession {
  switch (e.type) {
    case "SCORE_SET": {
      if (s.status !== "active" || !inRange(s, e.holeIndex)) return s;
      const strokes = clampStrokes(e.strokes);
      const current = s.entries[e.holeIndex];
      if (current?.strokes === strokes) return s;
      const entries = [...s.entries];
      entries[e.holeIndex] = {
        strokes,
        updatedAt: e.at,
        location: e.location ?? null,
      };
      return accept(s, { entries }, e.at);
    }
    case "SCORE_CLEARED": {
      if (s.status !== "active" || !inRange(s, e.holeIndex)) return s;
      const current = s.entries[e.holeIndex];
      if (current?.strokes === null) return s;
      const entries = [...s.entries];
      entries[e.holeIndex] = { strokes: null, updatedAt: e.at };
      return accept(s, { entries }, e.at);
    }
    case "HOLE_SELECTED": {
      if (s.status !== "active" || !inRange(s, e.holeIndex)) return s;
      if (s.currentHoleIndex === e.holeIndex) return s;
      return accept(s, { currentHoleIndex: e.holeIndex }, e.at);
    }
    case "NOTES_SET": {
      if (s.status === "submitted" || s.notes === e.notes) return s;
      return accept(s, { notes: e.notes }, e.at);
    }
    case "FINISH_STARTED": {
      if (s.status !== "active") return s;
      return accept(s, { status: "finishing" }, e.at);
    }
    case "FINISH_CANCELLED": {
      if (s.status !== "finishing") return s;
      return accept(s, { status: "active" }, e.at);
    }
    case "SUBMITTED": {
      if (s.status !== "finishing") return s;
      return accept(s, { status: "submitted" }, e.at);
    }
  }
}

/**
 * Auto-advance target after scoring hole `justScoredIndex`: the first
 * unscored hole strictly after it, wrapping around once; if every hole is
 * scored, stay put (the UI then spotlights Finish).
 */
export function nextHoleAfterScore(
  s: RoundSession,
  justScoredIndex: number,
): number {
  for (let step = 1; step <= s.holeCount; step += 1) {
    const i = (justScoredIndex + step) % s.holeCount;
    if (s.entries[i]?.strokes === null) return i;
  }
  return justScoredIndex;
}
