/**
 * Pure reducer for live round sessions. No React, no Expo, no I/O — every
 * transition is (session, event) → session, and a rejected/no-op event
 * returns the SAME reference so callers can skip persistence and renders.
 * That same-reference rule is also the engine-level double-tap guard.
 */
import { getDisplayedHoles } from "@/lib/scorecard";
import type {
  HoleEntry,
  RoundSession,
  SessionCourse,
  SessionEvent,
} from "@/lib/round-session/types";
import { SESSION_SCHEMA_VERSION } from "@/lib/round-session/types";
import type { Tee } from "@handicappin/handicap-core";

export const MIN_STROKES = 1;
export const MAX_STROKES = 30;
export const MAX_PUTTS = 20;
export const MAX_PENALTIES = 10;

export interface StartSessionParams {
  /** uuid — generated by the caller (expo-crypto) so the engine stays pure. */
  id: string;
  userId: string;
  course: SessionCourse;
  tee: Tee;
  holeCount: 9 | 18;
  nineHoleSection?: "front" | "back";
  /** Track detailed stats for this round (plan 013 D3). Default false. */
  detailed?: boolean;
  /** ISO timestamp for startedAt/lastEventAt. */
  now: string;
}

export function startSession(params: StartSessionParams): RoundSession {
  const { id, userId, course, tee, holeCount, nineHoleSection, detailed, now } =
    params;
  if (holeCount === 9 && nineHoleSection === undefined) {
    throw new Error("nineHoleSection is required for a 9-hole session");
  }
  const displayedHoles = getDisplayedHoles(
    { holes: tee.holes },
    holeCount,
    nineHoleSection ?? "front",
  );
  if (displayedHoles.length !== holeCount) {
    throw new Error(
      `Tee snapshot yielded ${displayedHoles.length} holes, expected ${holeCount}`,
    );
  }
  const entries: HoleEntry[] = Array.from({ length: holeCount }, () => ({
    strokes: null,
    updatedAt: now,
  }));
  return {
    schemaVersion: SESSION_SCHEMA_VERSION,
    id,
    userId,
    status: "active",
    startedAt: now,
    lastEventAt: now,
    eventSeq: 0,
    course,
    tee,
    holeCount,
    ...(holeCount === 9 ? { nineHoleSection } : {}),
    ...(detailed ? { detailed } : {}),
    displayedHoles,
    currentHoleIndex: 0,
    entries,
    notes: "",
  };
}

const clampStrokes = (strokes: number): number =>
  Math.min(MAX_STROKES, Math.max(MIN_STROKES, Math.round(strokes)));

const inRange = (s: RoundSession, holeIndex: number): boolean =>
  Number.isInteger(holeIndex) && holeIndex >= 0 && holeIndex < s.holeCount;

/** Accepted event bookkeeping: bump eventSeq, stamp lastEventAt. */
const accept = (s: RoundSession, patch: Partial<RoundSession>, at: string) => ({
  ...s,
  ...patch,
  eventSeq: s.eventSeq + 1,
  lastEventAt: at,
});

export function applyEvent(s: RoundSession, e: SessionEvent): RoundSession {
  switch (e.type) {
    case "SCORE_SET": {
      if (s.status !== "active" || !inRange(s, e.holeIndex)) return s;
      // NaN would defeat the same-reference idempotence check below
      // (NaN !== NaN) and poison the persisted session — the engine is a
      // protocol surface (future watch events), so don't trust callers.
      if (!Number.isFinite(e.strokes)) return s;
      const strokes = clampStrokes(e.strokes);
      const current = s.entries[e.holeIndex];
      if (current?.strokes === strokes) return s;
      const entries = [...s.entries];
      // Preserve hole-out detail on a score edit — re-scoring a hole must
      // never wipe putts/fairway/penalties already captured for it — but
      // re-fit it to the new score: putts + penalties ≤ strokes − 1 (putts
      // keep priority). Mirrored in Engine.swift.
      const budget = Math.max(0, strokes - 1);
      const putts =
        current?.putts == null ? current?.putts : Math.min(current.putts, budget);
      const penaltyStrokes =
        current?.penaltyStrokes == null
          ? current?.penaltyStrokes
          : Math.min(current.penaltyStrokes, budget - (putts ?? 0));
      entries[e.holeIndex] = {
        ...current,
        ...(putts !== undefined ? { putts } : {}),
        ...(penaltyStrokes !== undefined ? { penaltyStrokes } : {}),
        strokes,
        updatedAt: e.at,
        location: e.location ?? null,
      };
      return accept(s, { entries }, e.at);
    }
    case "SCORE_CLEARED": {
      if (s.status !== "active" || !inRange(s, e.holeIndex)) return s;
      const current = s.entries[e.holeIndex];
      if (current?.strokes === null) return s;
      const entries = [...s.entries];
      // Clearing a score clears the whole hole — detail without strokes is
      // meaningless once the score is retracted.
      entries[e.holeIndex] = { strokes: null, updatedAt: e.at };
      return accept(s, { entries }, e.at);
    }
    case "HOLE_DETAIL_SET": {
      if (s.status !== "active" || !inRange(s, e.holeIndex)) return s;
      const current = s.entries[e.holeIndex];
      if (!current) return s;
      // Patch semantics: PRESENT key overwrites (null clears), ABSENT key
      // leaves the field alone. Numeric fields are validated, not trusted —
      // this is a protocol surface (watch events cross a codebase boundary).
      const clampDetail = (
        value: number | null | undefined,
        max: number,
      ): number | null | undefined => {
        if (value === undefined) return undefined;
        if (value === null) return null;
        if (!Number.isFinite(value)) return undefined;
        return Math.min(max, Math.max(0, Math.round(value)));
      };
      const putts = "putts" in e ? clampDetail(e.putts, MAX_PUTTS) : undefined;
      const penaltyStrokes =
        "penaltyStrokes" in e
          ? clampDetail(e.penaltyStrokes, MAX_PENALTIES)
          : undefined;
      const fairwayHit = "fairwayHit" in e ? e.fairwayHit : undefined;
      const next: HoleEntry = {
        ...current,
        ...(putts !== undefined ? { putts } : {}),
        ...(fairwayHit !== undefined ? { fairwayHit } : {}),
        ...(penaltyStrokes !== undefined ? { penaltyStrokes } : {}),
      };
      // A scored hole also bounds detail: putts + penalties ≤ strokes − 1
      // (putts keep priority). Unscored holes stay unbounded — detail can
      // land before the score in live play. Mirrored in Engine.swift.
      if (current.strokes !== null && current.strokes !== undefined) {
        const budget = Math.max(0, current.strokes - 1);
        if (next.putts != null) next.putts = Math.min(next.putts, budget);
        if (next.penaltyStrokes != null) {
          next.penaltyStrokes = Math.min(
            next.penaltyStrokes,
            budget - (next.putts ?? 0),
          );
        }
      }
      if (
        (next.putts ?? null) === (current.putts ?? null) &&
        (next.fairwayHit ?? null) === (current.fairwayHit ?? null) &&
        (next.penaltyStrokes ?? null) === (current.penaltyStrokes ?? null)
      ) {
        return s;
      }
      next.updatedAt = e.at;
      const entries = [...s.entries];
      entries[e.holeIndex] = next;
      return accept(s, { entries }, e.at);
    }
    case "HOLE_SELECTED": {
      if (s.status !== "active" || !inRange(s, e.holeIndex)) return s;
      if (s.currentHoleIndex === e.holeIndex) return s;
      return accept(s, { currentHoleIndex: e.holeIndex }, e.at);
    }
    case "NOTES_SET": {
      if (s.status === "submitted" || s.notes === e.notes) return s;
      return accept(s, { notes: e.notes }, e.at);
    }
    case "FINISH_STARTED": {
      if (s.status !== "active") return s;
      return accept(s, { status: "finishing" }, e.at);
    }
    case "FINISH_CANCELLED": {
      if (s.status !== "finishing") return s;
      return accept(s, { status: "active" }, e.at);
    }
    case "SUBMITTED": {
      if (s.status !== "finishing") return s;
      return accept(s, { status: "submitted" }, e.at);
    }
  }
}

/**
 * Auto-advance target after scoring hole `justScoredIndex`: the first
 * unscored hole strictly after it, wrapping around once; if every hole is
 * scored, stay put (the UI then spotlights Finish).
 */
export function nextHoleAfterScore(
  s: RoundSession,
  justScoredIndex: number,
): number {
  for (let step = 1; step <= s.holeCount; step += 1) {
    const i = (justScoredIndex + step) % s.holeCount;
    if (s.entries[i]?.strokes === null) return i;
  }
  return justScoredIndex;
}
