import { FormRound } from "@/types/round";

export const roundZero: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 72,
    slope: 113,
    par: 36,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 7,
      hcpStrokes: 1,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 10,
      par: 3,
      hcp: 10,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 11,
      par: 3,
      hcp: 11,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 12,
      par: 3,
      hcp: 12,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 13,
      par: 3,
      hcp: 13,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 14,
      par: 3,
      hcp: 14,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 15,
      par: 3,
      hcp: 15,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 16,
      par: 3,
      hcp: 16,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 17,
      par: 3,
      hcp: 17,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 18,
      par: 3,
      hcp: 18,
      strokes: 7,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 18,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-06-23T12:00:00Z"),
};

export const roundOne: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 5,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-06-23T12:00:00Z"),
};

export const roundTwo: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 4,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-06-29T12:00:00Z"),
};

export const roundThree: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 8,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 4,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-06-26T12:00:00Z"),
};

export const roundFour: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 3,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-07-01T12:00:00Z"),
};

export const roundFive: FormRound = {
  courseInfo: {
    location: "Norhaug",
    courseRating: 54.8,
    slope: 86,
    par: 28,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 4,
      hcp: 3,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 5,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-07-02T12:00:00Z"),
};

export const roundSix: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 4,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-07-06T12:00:00Z"),
};

export const roundSeven: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 3,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 7,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-07-08T12:00:00Z"),
};

export const roundEight: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 3,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-07-09T12:00:00Z"),
};

export const roundNine: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 3,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 6,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-07-11T12:00:00Z"),
};

export const roundTen: FormRound = {
  courseInfo: {
    location: "Ballerud",
    courseRating: 50.3,
    slope: 82,
    par: 27,
  },
  holes: [
    {
      holeNumber: 1,
      par: 3,
      hcp: 1,
      strokes: 5,
      hcpStrokes: 0,
    },
    {
      holeNumber: 2,
      par: 3,
      hcp: 2,
      strokes: 7,
      hcpStrokes: 0,
    },
    {
      holeNumber: 3,
      par: 3,
      hcp: 3,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 4,
      par: 3,
      hcp: 4,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 5,
      par: 3,
      hcp: 5,
      strokes: 4,
      hcpStrokes: 0,
    },
    {
      holeNumber: 6,
      par: 3,
      hcp: 6,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 7,
      par: 3,
      hcp: 7,
      strokes: 6,
      hcpStrokes: 0,
    },
    {
      holeNumber: 8,
      par: 3,
      hcp: 8,
      strokes: 3,
      hcpStrokes: 0,
    },
    {
      holeNumber: 9,
      par: 3,
      hcp: 9,
      strokes: 6,
      hcpStrokes: 0,
    },
  ],
  numberOfHoles: 9,
  userId: "6b46ccce-9cfc-41d2-809f-66b737fcb654",
  date: new Date("2024-07-13T12:00:00Z"),
};

export const rounds = [
  roundOne,
  roundTwo,
  roundThree,
  roundFour,
  roundFive,
  roundSix,
  roundSeven,
  roundEight,
  roundNine,
  roundTen,
];
