#!/bin/bash
# Build combined seed.sql from base + all course SQL files

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

SEED_BASE="$PROJECT_ROOT/supabase/seed-base.sql"
SEED_OUTPUT="$PROJECT_ROOT/supabase/seed.sql"
COURSES_DIR="$PROJECT_ROOT/scripts/sql"

echo "Building seed.sql..."

# Start with the base seed file
cat "$SEED_BASE" > "$SEED_OUTPUT"

# Add a separator comment
echo "" >> "$SEED_OUTPUT"
echo "-- ============================================" >> "$SEED_OUTPUT"
echo "-- Additional course data from scripts/sql/" >> "$SEED_OUTPUT"
echo "-- Generated by scripts/build-seed.sh" >> "$SEED_OUTPUT"
echo "-- ============================================" >> "$SEED_OUTPUT"

# Append all SQL files from scripts/sql/
file_count=0
for sql_file in "$COURSES_DIR"/*.sql; do
  if [ -f "$sql_file" ]; then
    filename=$(basename "$sql_file")
    echo "" >> "$SEED_OUTPUT"
    echo "-- Source: scripts/sql/$filename" >> "$SEED_OUTPUT"
    cat "$sql_file" >> "$SEED_OUTPUT"
    ((++file_count))
  fi
done

echo "✓ Combined seed-base.sql + $file_count course files into seed.sql"
